Repository NishikantaRay/Losit, pull requests merged in 2021-10, with the labels that each got.

#15 Added LoginPage
  loginpage new/index.css
  loginpage new/index.html
  loginpage new/index.js
Labels: Hacktoberfest21, Hacktoberfest

#16 Added Contactus Page
  contactpage/index.css
  contactpage/index.html
Labels: Hacktoberfest21, Hacktoberfest

#17 Signup page added using glassmorphism
  Annotation 2021-10-01 221944.png
  README.md
  glasslogin.html
Labels: Hacktoberfest21, Hacktoberfest

#19 Sigin Page
  Signupage_ashish.html
  style_Ashish.css
Labels: Hacktoberfest21, Hacktoberfest

#20 Added neumorphism login page
  neumorphism login/index.css
  neumorphism login/neumorphismindex.html
Labels: Hacktoberfest, hacktoberfest-accepted

#21 Added Glass Login Page
  Glass Login/glassloginindex.css
  Glass Login/glassloginindex.html
Labels: Hacktoberfest, hacktoberfest-accepted

#23 Added a form for signup.
  SignUp/simpleForm.html
Labels: Hacktoberfest, hacktoberfest-accepted

#24 sign in form project
  Login Form/signInform.html
Labels: Hacktoberfest, hacktoberfest-accepted

#25 Added a transparent simple login page
  login1/bg.jpg
  login1/login.html
  login1/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#26 Added another Form
  SignUp/Form.html
Labels: Hacktoberfest, hacktoberfest-accepted

#27 New Login Page Added
  Login Form/loginform/loginindex.css
  Login Form/loginform/loginindex.html
Labels: Hacktoberfest, hacktoberfest-accepted

#29 bs5 login added
  login bs5/login.css
  login bs5/login.html
  neumorplogin/neumorlogin.css
  neumorplogin/neumorlogin.html
Labels: Hacktoberfest, hacktoberfest-accepted

#28 New Sign Up Page Added
  Glass Login/glassloginpage/index.css
  Glass Login/glassloginpage/index.html
  Glass Login/glassloginpage/index.js
  SignUp/signuppage/signupindex.css
  SignUp/signuppage/signupindex.html
  contactpage/contactuspage/index.css
  contactpage/contactuspage/index.html
  contactpage/contactuspage/index.js
Labels: Hacktoberfest, hacktoberfest-accepted

#30 Glass Sign Up with Bootstrap5
  Glass Signup/Glass-SignUp.html
Labels: Hacktoberfest, hacktoberfest-accepted

#31 Added #10 issue files using react.
  react-login-register-master/README.md
  react-login-register-master/package-lock.json
  react-login-register-master/package.json
  react-login-register-master/public/favicon.ico
  react-login-register-master/public/index.html
  react-login-register-master/public/manifest.json
  react-login-register-master/src/App.jsx
  react-login-register-master/src/App.scss
  react-login-register-master/src/App.test.js
  react-login-register-master/src/components/login/index.jsx
  react-login-register-master/src/components/login/login.jsx
  react-login-register-master/src/components/login/register.jsx
  react-login-register-master/src/components/login/style.scss
  react-login-register-master/src/index.css
  react-login-register-master/src/index.js
  react-login-register-master/src/login.svg
  react-login-register-master/src/logo.svg
  react-login-register-master/src/serviceWorker.js
  react-login-register-master/yarn.lock
Labels: Hacktoberfest, hacktoberfest-accepted

#34 Login Template
  Animated Login/form.css
  Animated Login/form.html
Labels: Hacktoberfest, hacktoberfest-accepted

#33 Sliding Sign In SignUp Page
  SignIn-SignUp-Page/img1.jpg
  SignIn-SignUp-Page/img2.jpg
  SignIn-SignUp-Page/index.html
  SignIn-SignUp-Page/logo.jpg
  SignIn-SignUp-Page/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#32 3rd Form
  SignUppage-9/ContactForm.html
Labels: Hacktoberfest, hacktoberfest-accepted

#35 Form added
  SignUppage-9/Login.html
Labels: Hacktoberfest, hacktoberfest-accepted

#38 Jayesh Sign In Sign Up page
  Sign In Sign Up Page/index.html
  Sign In Sign Up Page/script.js
  Sign In Sign Up Page/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#36 Create LoginSignup.html
  HtmlCssJsForm.html
  LoginSignup.html
  loginagain.html
Labels: Hacktoberfest, hacktoberfest-accepted

#44 Bootstrap Login Page
  Simple-Bootstrap-Login/.gitignore
  Simple-Bootstrap-Login/background(2).jpg
  Simple-Bootstrap-Login/background.png
  Simple-Bootstrap-Login/color-pencils.svg
  Simple-Bootstrap-Login/login.html
  Simple-Bootstrap-Login/loginportal.html
  Simple-Bootstrap-Login/mystyle.css
  Simple-Bootstrap-Login/styles1.css
Labels: Hacktoberfest, hacktoberfest-accepted

#48 added a animated form made using html,css,javascript
  animated signin login/images/undraw_Welcome_re_h3d9.svg
  animated signin login/images/undraw_teacher_35j2.svg
  animated signin login/index.html
  animated signin login/script.js
  animated signin login/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#47 Login-Page-and-Signup-Page-with-Validation Added
  Login-Page-and-Signup-Page-with-Validation/home.css
  Login-Page-and-Signup-Page-with-Validation/home.html
  Login-Page-and-Signup-Page-with-Validation/img/body-bg-img.png
  Login-Page-and-Signup-Page-with-Validation/login.html
  Login-Page-and-Signup-Page-with-Validation/login.js
  Login-Page-and-Signup-Page-with-Validation/signup.html
  Login-Page-and-Signup-Page-with-Validation/signup.js
  Login-Page-and-Signup-Page-with-Validation/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#49 Development
  README.md
  loginpage-21/index.html
  loginpage-21/landingpage3.png
  loginpage-21/style.css
  loginpage20/index.html
  loginpage20/landingpage4.png
  loginpage20/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#66 Development
  README.md
  loginpage-22/index.html
  loginpage-22/landingpage-5.png
  loginpage-22/style.css
Labels: Hacktoberfest21, Hacktoberfest, hacktoberfest-accepted

#70 Tailwind css login and signup page
  Tailwind-css-login-and-signup-page/login.html
  Tailwind-css-login-and-signup-page/login1.html
  Tailwind-css-login-and-signup-page/signup.html
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#68 Adding a new Neumorphic Login Page
  Neumorphic-UI-Login-Form/index.html
  Neumorphic-UI-Login-Form/styles.css
  Neumorphic-UI-Login-Form/styles.css.map
  Neumorphic-UI-Login-Form/styles.scss
Labels: Hacktoberfest, hacktoberfest-accepted

#71 Facebook Login Page
  Facebook-Login-Page/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#67 login page by @ankit25032
  AmazingLoginPage/images/back.jpg
  AmazingLoginPage/index.css
  AmazingLoginPage/index.html
  glassloginpage/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#75 sopity clone added mobile responsive
  Spotify-Login-Page/.DS_Store
  Spotify-Login-Page/assets/.DS_Store
  Spotify-Login-Page/assets/images/chris-stapleton.jpg
  Spotify-Login-Page/assets/images/facebook-icon.svg
  Spotify-Login-Page/assets/images/favicon.ico
  Spotify-Login-Page/assets/images/instagram-icon.svg
  Spotify-Login-Page/assets/images/jennifer-lopez.jpg
  Spotify-Login-Page/assets/images/joji.jpg
  Spotify-Login-Page/assets/images/machine-gun-kelly.jpg
  Spotify-Login-Page/assets/images/profile-arrow.svg
  Spotify-Login-Page/assets/images/profile-icon.svg
  Spotify-Login-Page/assets/images/spotify-logo.svg
  Spotify-Login-Page/assets/images/travis-scott.jpg
  Spotify-Login-Page/assets/images/twitter-icon.svg
  Spotify-Login-Page/assets/images/us.svg
  Spotify-Login-Page/assets/images/zayn.jpg
  Spotify-Login-Page/css/albums.css
  Spotify-Login-Page/css/base.css
  Spotify-Login-Page/css/footer.css
  Spotify-Login-Page/css/header.css
  Spotify-Login-Page/css/hero.css
  Spotify-Login-Page/css/media-queries.css
  Spotify-Login-Page/index.html
  Spotify-Login-Page/js/script.js
Labels: Hacktoberfest, hacktoberfest-accepted

#79 Added Heroku login page
  Heroku-Login-Page/index.html
  Heroku-Login-Page/styles.css
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#78 Added Zomato clone
  Zomato_Clone/home.html
  Zomato_Clone/images/1 (1).png
  Zomato_Clone/images/1.jpg
  Zomato_Clone/images/1.png
  Zomato_Clone/images/2.jpg
  Zomato_Clone/images/3.jpg
  Zomato_Clone/images/4.jpg
  Zomato_Clone/images/cat1.png
  Zomato_Clone/images/cat2.png
  Zomato_Clone/images/cat3.png
  Zomato_Clone/images/cat4.png
  Zomato_Clone/images/cat5.png
  Zomato_Clone/images/cat6.png
  Zomato_Clone/images/cat7.png
  Zomato_Clone/images/cat8.png
  Zomato_Clone/images/category_1.jpg
  Zomato_Clone/images/category_1.png
  Zomato_Clone/images/order_background.jpg
  Zomato_Clone/images/pizza.jpg
  Zomato_Clone/images/pizza3.png
Labels: Hacktoberfest, hacktoberfest-accepted

#77 added the instagram login page
  Instagram Login Page/fonts/segoe-ui-bold.ttf
  Instagram Login Page/fonts/segoe-ui-regular.ttf
  Instagram Login Page/images/applestore.png
  Instagram Login Page/images/facebook-icon.png
  Instagram Login Page/images/favicon.ico
  Instagram Login Page/images/googlestore.png
  Instagram Login Page/images/instagram-logo.png
  Instagram Login Page/images/phones.png
  Instagram Login Page/index.html
  Instagram Login Page/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#76 Twitter loginpage clone
  Twitter-Loginpage-Clone/index.html
  Twitter-Loginpage-Clone/logo.png
  Twitter-Loginpage-Clone/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#81 Google Page added
  Google-Login-Clone/.gitignore
  Google-Login-Clone/images/favicon.jpg
  Google-Login-Clone/images/logo.jpg
  Google-Login-Clone/index.html
  Google-Login-Clone/main.js
  Google-Login-Clone/styles.css
  Zomato-Login-Page/.gitignore
  Zomato-Login-Page/assets/images/nightLife.jpeg
  Zomato-Login-Page/assets/images/zomatoBurger.jpeg
  Zomato-Login-Page/assets/images/zomatoDownload.png
  Zomato-Login-Page/assets/images/zomatoGold.jpeg
  Zomato-Login-Page/assets/images/zomatoPhone.webp
  Zomato-Login-Page/assets/images/zomatoSamosa.jpeg
  Zomato-Login-Page/css/login.css
  Zomato-Login-Page/css/styles.css
  Zomato-Login-Page/index.html
  zomato-page/.gitignore
  zomato-page/assets/images/nightLife.jpeg
  zomato-page/assets/images/zomatoBurger.jpeg
  zomato-page/assets/images/zomatoDownload.png
  zomato-page/assets/images/zomatoGold.jpeg
  zomato-page/assets/images/zomatoPhone.webp
  zomato-page/assets/images/zomatoSamosa.jpeg
  zomato-page/css/login.css
  zomato-page/css/styles.css
  zomato-page/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#82 LinkedIn login page clone
  LinkedIn login page clone/index.html
  LinkedIn login page clone/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#83 github login page added
  github-login/fluidicon.png
  github-login/index.html
  github-login/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#85 Paypal login page design added (fix: #60)
  Paypal Login Page/index.html
  Paypal Login Page/pp-logo.png
  Paypal Login Page/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#88 React Login/Signup with Validation
  react_login/.gitignore
  react_login/README.md
  react_login/package-lock.json
  react_login/package.json
  react_login/public/favicon.ico
  react_login/public/index.html
  react_login/public/manifest.json
  react_login/src/App.test.tsx
  react_login/src/App.tsx
  react_login/src/index.tsx
  react_login/src/react-app-env.d.ts
  react_login/src/reportWebVitals.ts
  react_login/src/setupTests.ts
  react_login/src/styles/Main.scss
  react_login/src/styles/components/_Custom.scss
  react_login/src/styles/components/_Resets.scss
  react_login/tsconfig.json
Labels: Hacktoberfest, hacktoberfest-accepted
