Repository NishikantaRay/Losit, pull requests merged in 2022-10, with the labels that each got.

#132 Added one sign up page
  Pages/signup-page-1_2022/index.html
  Pages/signup-page-1_2022/style.css
Labels: Hacktoberfest

#145 update
  frontend/src/App.js
  frontend/src/Footer.js
  frontend/src/FooterSocialLink.js
Labels: Hacktoberfest22, Hacktoberfest, hacktoberfest-accepted

#148 added middleware and localhost server
  backend/index.js
  backend/middleware/auth.js
  backend/middleware/logger.js
Labels: good first issue, Hacktoberfest22, Hacktoberfest, hacktoberfest-accepted

#154 contributor guidelines added
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#155 added card model
  backend/model/card.model.js
Labels: good first issue, Hacktoberfest22, Hacktoberfest, hacktoberfest-accepted

#156 Create a api for add listing card data
  backend/config/db.config.js
  backend/index.js
  backend/model/card.model.js
  backend/route/card.route.js
Labels: hacktoberfest-accepted

#157 Added get all card route
  backend/route/card.route.js
Labels: hacktoberfest-accepted

#161 Update Card Api
  backend/route/card.route.js
Labels: Hacktoberfest22, hacktoberfest-accepted

#160 Get All Cards having similar keyword in title or description of a card
  backend/route/card.route.js
Labels: Hacktoberfest22, hacktoberfest-accepted

#163 Get All Cards having similar keyword in title or description of a card
  backend/route/card.route.js
Labels: Hacktoberfest22, hacktoberfest-accepted
